version: "3"

networks:
  mymonitoring:

services:
  otel-collector:
    container_name: otel
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./etc/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679"
    networks:
      - mymonitoring

  loki:
    container_name: loki
    image: grafana/loki:3.1.0
    environment:
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://loki:3100/otlp/v1/logs
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki-config.yaml
    volumes:
      - ./etc/loki-config.yaml:/etc/loki-config.yaml
    networks:
      - mymonitoring

  # Jaeger
  # jaeger-all-in-one:
  #   container_name: jaeger
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_ZIPKIN_HOST_PORT=9411
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "14250:14250"
  #     - "9411:9411"
  #     # - "4317:4317"
  #     # - "4318:4318"
  #   networks:
  #     - mymonitoring
  #
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN=true
    volumes:
      # - ./volumes/grafana:/var/lib/grafana
      - ./etc/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "4000:3000"
    networks:
      - mymonitoring
