version: "3"

networks:
  liftgrafana:

services:
  loki:
    container_name: loki
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./etc/:/etc/loki
    networks:
      - liftgrafana

  # Jaeger
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - liftgrafana

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    ports:
      - "4000:3000"
    networks:
      - liftgrafana
